### PR TITLE
[DRAFT] feature: complete round trip for git sync with bitbucket

### PR DESCRIPTION
**Pull request by TheeMattOliver**
> [!NOTE]  
> Draft while WIP; completing unit tests.

**Todo before merge**

- [x] check complete round trip (read from and push to Bitbucket)
- [ ] add unit tests

Completes round trip for git sync with Bitbucket.

Closes https://github.com/tokens-studio/figma-plugin/issues/380

https://github.com/tokens-studio/figma-plugin/assets/9900326/efe946fd-e9ea-4600-93c0-84d64d616cb3

### CODE REVIEW

**Comment by william-cooley-actabl** [comment]
What help are you needing with this feature for it to be approved and merged in? Is there a criteria specification that is needing to be met, or is this just a working draft proposal?

**Comment by six7** [comment]
We'll merge this in to our 2.0 branch which will undergo a test phase

**Comment by six7** [comment]
This is great, thanks Matt!

I went ahead and [rebased](https://github.com/tokens-studio/figma-plugin/pull/2512) this on our `release-139` branch, which is the branch for our 2.0 release.

I did notice that branch switching does not work yet, other than that it seemed to work fine 🎉 

Thank you!

**Comment by six7** [comment]
Closing this, changes have been merged into the 2.0 branch. Again, thank you so much for this! ❤

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❇️ Bitbucket - sync provider added](https://tokensstudio.featurebase.app/p/bitbucket-sync-provider-added)

**Pull request closed without merging**
