### PR TITLE
chore: add action to post link to built artifact

### PR DESCRIPTION
**Pull request by cuserox**
### Why does this PR exist?

Make it easier to share individual builds to test.

### What does this pull request do?

* Adds an action [after the artifact is stored](https://github.com/tokens-studio/figma-plugin/blob/release-139/.github/workflows/node.js.yml#L32) that posts a link to download it. Runs on every CI once a PR is created.
* Uses `actions/upload-artifact@v4` to have access to the `artifact-url` it outputs. Older versions will also be deprecated soon 👉 [read more here](https://github.com/actions/upload-artifact?tab=readme-ov-file#actionsupload-artifact)

### Testing this change

[See automated comment below](https://github.com/tokens-studio/figma-plugin/pull/3029#issuecomment-2250833012) 😄

### CODE REVIEW

**Comment by macintoshhelper** [comment]
Awesome! 🎉 

Would be nice to avoid creating a new comment for every commit (and avoid notification after the first comment). Could use something like this: https://github.com/marketplace/actions/create-or-update-comment 🙂

**Comment by cuserox** [comment]
> Awesome! 🎉
> 
> Would be nice to avoid creating a new comment for every commit (and avoid notification after the first comment). Could use something like this: https://github.com/marketplace/actions/create-or-update-comment 🙂

Nice, I'll adapt it to post on the first run, then update it on subsequent runs 👀 New action discovered. Thanks!

**Review by macintoshhelper — APPROVED** [review]
LGTM! 🎉

**Comment by six7** [comment]
🎉  This is _AWESOME_! Thank you!!

**Pull request merged**
