### PR TITLE
1997-variables-when-syncing-with-ado-the-link-to-variables-get-lost

### PR DESCRIPTION
**Pull request by swordEdge**
https://github.com/tokens-studio/figma-plugin/assets/25951419/a1dfa02e-b08b-4402-8d8d-65cdc1d6cd24

### CODE REVIEW

**Review by SorsOps — APPROVED** [review]

**Comment by SorsOps** [comment]
Just need to address the failing tests

**Review by SorsOps — CHANGES_REQUESTED** [review]
Just need to address test failures

**Comment by keeganedwin** [comment]
@swordEdge issue is still present - theme-groups are disordered after pulling from repo
https://github.com/tokens-studio/figma-plugin/assets/93133012/aae23334-d6ff-498d-8bbc-d83bf10a3e70

**Comment by rbosker** [comment]
this is working as expected now

**Review by SorsOps — APPROVED** [review]

**Pull request merged**
