### PR TITLE
GitLab sync: Include inherited members when checking for write permissions

### PR DESCRIPTION
**Pull request by robin-ambachtsheer**
We're currently blocked from using the plugin because after connecting to our private GitLab server the plugin refuses to let us write any changes (even though it was able to create a commit with the new json file).

After some debugging we found that the GitLab API was returning a 404 error when trying to fetch the member data for the project. This is because our GitLab repository inherits the members from another group and it doesn't have any direct members itself. To get all the members including the inherited ones you need to fetch another endpoint.

By including the `includeInherited` option in the calls to `GroupMembers` and `ProjectMembers` from the `@gitbeaker/browser` package this issue will be resolved for us as it will hit the correct endpoint. According to GitLab's own documentation this should include all members at all times https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project-including-inherited-and-invited-members, so it should not have any impact on existing use cases.

### CODE REVIEW

**Comment by robin-ambachtsheer** [comment]
@six7 would you mind giving this a look? It's blocking our usage and we'd love to move forward with integrating your fantastic plugin into our process.

**Comment by six7** [comment]
Actually could you update tests so they're not failing? I guess we'll just need to update those with the now added additional parameter.

**Review by six7 — CHANGES_REQUESTED** [review]
Actually could you update tests so they're not failing? I guess we'll just need to update those with the now added additional parameter.

**Comment by robin-ambachtsheer** [comment]
Of course, sorry I thought I had run the tests but apparently not. Added the additional parameter to the tests.

**Comment by six7** [comment]
Awesome, thank you! I'll merge this in tomorrow morning and release this 🙏

**Pull request merged**
